FROM golang:1.22.3
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app

RUN apt update \
    && apt install --no-install-recommends --assume-yes \
      libclang-dev \
    && rm -rf /var/lib/apt/lists/*

# install dependencies
COPY go.mod go.sum ./
RUN go mod download

# build binary
COPY . .
RUN GOOS=linux go build -o /obscurio ./main.go

EXPOSE 5432
EXPOSE 80

ENTRYPOINT ["/obscurio"]